modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "blocktracker"
version = "${version}"
displayName = "BlockTrackerApi"
authors = "Kall"
description = '''
Track the blocks in your worlds.
'''
#logoFile = ""